DROP DATABASE IF EXISTS billingservice;
DROP USER IF EXISTS `billing_service`@`%`;
CREATE DATABASE IF NOT EXISTS billingservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `billing_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `billingservice`.* TO `billing_service`@`%`;
FLUSH PRIVILEGES;

